FROM node:20-alpine AS build

# アプリケーションディレクトリを作成
WORKDIR /usr/src/app

# パッケージの依存関係をコピー
COPY ./backend/package*.json ./

# 依存関係をインストール
RUN npm install

FROM node:20-alpine AS production

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

# アプリケーションのソースコードをコピー
COPY ./backend .

# アプリケーションがリッスンするポートを公開
EXPOSE 3000

# アプリケーションを起動
CMD ["npm", "run", "start"]
